# Site settings
title: ara dev - code snippets
header-img: img/home-bg.jpg
email: your-email@yourdomain.com
description: "Java EE architecture, design and development tips, hints, code snippets and other random ideas."
baseurl: ""
url: "http://www.aracrown.org"
twitter_username: aracrown
github_username:  aracrown
facebook_username:  aracrown

# Build settings
markdown: kramdown
highlighter: pygments
permalink: /blog/:categories/:title/
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
