# Site settings
title: ara dev
header-img: img/home-bg.jpg
email: your-email@yourdomain.com
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "http://www.aracrown.org"
twitter_username: aracrown
github_username:  aracrown
facebook_username:  aracrown

# Build settings
markdown: kramdown
highlighter: pygments
permalink: /blog/:categories/:title/
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
